### ISSUE TITLE
no idea man

### ISSUE THREAD

**Issue by smokinghippoty** [BenWirus/ZombieVoters#5]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./grab_deaths.py", line 228, in <module>
    main(sys.argv[1:])
  File "./grab_deaths.py", line 224, in main
    run(int(year), int(page), str(county), str(state))
  File "./grab_deaths.py", line 186, in run
    chrome = webdriver.Chrome('./chromedriver')
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by smokinghippoty** [comment]
im using repl.it

**Comment by BenWirus** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: './chromedriver'`

Did you download the chromedriver binary from the url linked in the [setup section](https://github.com/BenWirus/ZombieVoters#setup) of the readme? After downloading it you'll need to extract the zip file and place the binary in the root of the project.

Just a heads up I'm currently rewriting this to use Firefox instead of Chrome, so if you update you'll have to set up the geckodriver instead of the chromedriver.

**Comment by Jambre** [comment]
Make sure you have the correct version of chromedriver for your Chrome version as well.

**Comment by smokinghippoty** [comment]
> `FileNotFoundError: [Errno 2] No such file or directory: './chromedriver'`
> 
> Did you download the chromedriver binary from the url linked in the [setup section](https://github.com/BenWirus/ZombieVoters#setup) of the readme? After downloading it you'll need to extract the zip file and place the binary in the root of the project.
> 
> Just a heads up I'm currently rewriting this to use Firefox instead of Chrome, so if you update you'll have to set up the geckodriver instead of the chromedriver.

using it in a website called repl.it if you get the time check it out?

**Comment by smokinghippoty** [comment]
> `FileNotFoundError: [Errno 2] No such file or directory: './chromedriver'`
> 
> Did you download the chromedriver binary from the url linked in the [setup section](https://github.com/BenWirus/ZombieVoters#setup) of the readme? After downloading it you'll need to extract the zip file and place the binary in the root of the project.
> 
> Just a heads up I'm currently rewriting this to use Firefox instead of Chrome, so if you update you'll have to set up the geckodriver instead of the chromedriver.

so i figured it out 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

driver = webdriver.Chrome(options=chrome_options)
driver.get("https://repl.it/@sergeichestakov/selenium")

**Comment by BenWirus** [comment]
I wouldn't worry about this to much. I figured out a much better way to do this using python requests and the GraphQL API on myheritage.com. I'm going to push an update today that's a complete rewrite.

**Comment by smokinghippoty** [comment]
> I wouldn't worry about this too much. I figured out a much better way to do this using python requests and the GraphQL API on myheritage.com. I'm going to push an update today that's a complete rewrite.

nice! i'll attempt to make a repl.it copy of it (with your permission)

**Comment by BenWirus** [comment]
You can do what ever you want with this! 👍  What exactly is repl.it?

**Comment by smokinghippoty** [comment]
its a sandbox online that you can import github projects and run it from there its a lot better than doing it on host honestly

**Comment by BenWirus** [comment]
Oh sounds cool, I'll check it out!

**Comment by smokinghippoty** [comment]
https://repl.it/join/bctfwdde-phantomghosmat

**Comment by smokinghippoty** [comment]
ben when you get time shoot me a request on discord Matto#5500

**Comment by BenWirus** [comment]
@smokinghippoty I probably won't have time today to hop on discord, If you have any questions I'll keep this issue open. I'll probably hop on discord tomorrow.

If you are interested check out the `myheritage` branch. It has a lot of improvements. Check out the README.md you'll likely have to start from scratch. But there are a lot of improvements, the main two being resumable segmented downloads and no need for Selenium and browsers since it's using an API. Let me know if you have any questions.

I'd like to organize a few people to download specific segments to speed things up and then share our results in a single git repo so we can get most of the death data quickly. Let me know if this is something you'd be interested in?

**Comment by smokinghippoty** [comment]
sure man!

**Comment by smokinghippoty** [comment]
hey ben i'll send you a collab invite when you add me
